dist: bionic

matrix:
  include:
    - name: PHP 7.1; HTTPlug 1
      env:
        - PHP_VERSION=7.1
        - HTTPPLUG_VERSION=^1.1
    - name: PHP 7.1; HTTPlug 2
      env:
        - PHP_VERSION=7.1
        - HTTPPLUG_VERSION=^2.0
    - name: PHP 7.2; HTTPlug 1
      env:
        - PHP_VERSION=7.2
        - HTTPPLUG_VERSION=^1.1
    - name: PHP 7.2; HTTPlug 2
      env:
        - PHP_VERSION=7.2
        - HTTPPLUG_VERSION=^2.0
    - name: PHP 7.3; HTTPlug 1
      env:
        - PHP_VERSION=7.3
        - HTTPPLUG_VERSION=^1.1
    - name: PHP 7.3; HTTPlug 2
      env:
        - PHP_VERSION=7.3
        - HTTPPLUG_VERSION=^2.0
    - name: PHP 7.4; HTTPlug 1
      env:
        - PHP_VERSION=7.4
        - HTTPPLUG_VERSION=^1.1
    - name: PHP 7.4; HTTPlug 2
      env:
        - PHP_VERSION=7.4
        - HTTPPLUG_VERSION=^2.0

before_install:
  - travis_retry docker pull registry.gitlab.com/grahamcampbell/php:$PHP_VERSION
  - docker run -it -w /data -v ${PWD}:/data:delegated --entrypoint composer registry.gitlab.com/grahamcampbell/php:$PHP_VERSION require "php-http/httplug:${HTTPPLUG_VERSION}" --no-update -n

install:
  - travis_retry docker run -it -w /data -v ${PWD}:/data:delegated --entrypoint composer registry.gitlab.com/grahamcampbell/php:$PHP_VERSION install --no-suggest --prefer-dist -n -o

script:
  - docker run -it -w /data -v ${PWD}:/data:delegated --entrypoint vendor/bin/phpunit registry.gitlab.com/grahamcampbell/php:$PHP_VERSION --coverage-clover build/logs/clover.xml

after_script:
  - travis_retry docker run -it -w /data -v ${PWD}:/data:delegated --entrypoint ocular registry.gitlab.com/grahamcampbell/php:$PHP_VERSION code-coverage:upload --format=php-clover build/logs/clover.xml
