name: Static

on:
  push:
  pull_request:
  schedule:
    - cron: '0 4 * * 1'

jobs:
  analyse:

    runs-on: ubuntu-latest

    name: PHPStan

    steps:
    - uses: actions/checkout@v2
    - name: Run Composer
      run: docker run --rm -w /data -v ${{ github.workspace }}:/data --entrypoint composer registry.gitlab.com/grahamcampbell/php:7.4-base update -n -o
    - name: Install PHPStan
      run: docker run --rm -w /data -v ${{ github.workspace }}:/data --entrypoint composer registry.gitlab.com/grahamcampbell/php:7.4-base bin phpstan update -n -o
    - name: Run PHPStan
      run: docker run --rm -w /data -v ${{ github.workspace }}:/data --entrypoint vendor/bin/phpstan registry.gitlab.com/grahamcampbell/php:7.4-cli analyse --no-progress
