name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 4 * * 1'

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.1, 7.2, 7.3, 7.4]

    name: PHP ${{ matrix.php }}

    steps:
    - uses: actions/checkout@v2
    - name: Run Composer
      run: docker run --rm -w /data -v ${{ github.workspace }}:/data --entrypoint composer registry.gitlab.com/grahamcampbell/php:${{ matrix.php }}-base update --prefer-dist -n -o
    - name: Run PHPUnit
      run: docker run --rm -w /data -v ${{ github.workspace }}:/data --entrypoint vendor/bin/phpunit registry.gitlab.com/grahamcampbell/php:${{ matrix.php }}-cli
